#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-aiofiles
Version  : 0.8.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/10/ca/c416cfacf6a47e1400dad56eab85aa86c92c6fbe58447d12035e434f0d5c/aiofiles-0.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/10/ca/c416cfacf6a47e1400dad56eab85aa86c92c6fbe58447d12035e434f0d5c/aiofiles-0.8.0.tar.gz
Summary  : File support for asyncio.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-aiofiles-license = %{version}-%{release}
Requires: pypi-aiofiles-python = %{version}-%{release}
Requires: pypi-aiofiles-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
aiofiles: file support for asyncio
==================================
.. image:: https://img.shields.io/pypi/v/aiofiles.svg
:target: https://pypi.python.org/pypi/aiofiles

%package license
Summary: license components for the pypi-aiofiles package.
Group: Default

%description license
license components for the pypi-aiofiles package.


%package python
Summary: python components for the pypi-aiofiles package.
Group: Default
Requires: pypi-aiofiles-python3 = %{version}-%{release}

%description python
python components for the pypi-aiofiles package.


%package python3
Summary: python3 components for the pypi-aiofiles package.
Group: Default
Requires: python3-core
Provides: pypi(aiofiles)

%description python3
python3 components for the pypi-aiofiles package.


%prep
%setup -q -n aiofiles-0.8.0
cd %{_builddir}/aiofiles-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641932131
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-aiofiles
cp %{_builddir}/aiofiles-0.8.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-aiofiles/c700a8b9312d24bdc57570f7d6a131cf63d89016
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-aiofiles/c700a8b9312d24bdc57570f7d6a131cf63d89016

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
